### ISSUE TITLE
AUTH_TOKEN

### ISSUE THREAD

**Issue by alexolliveira** [RealMQ/realmq-web-sdk#6]
Where can I find AUTH_TOKEN to start implementing RealMQ in my project? I didn't find it on realmq.com
const realmq = new RealMQ('<AUTH_TOKEN>');

**Comment by alrik** [comment]
@alexolliveira Sorry for this 1yr delay :open_mouth: 

If you are still interested, please drop us an email to service@realmq.com and we'll setup a demo account on our cloud platform.

Best, Alrik
